"""add entries, tags, entry_tags, entry_scripture_verses tables

Revision ID: 23850223500e
Revises: 7f1cdee3a012
Create Date: 2026-05-26 19:44:13.767202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23850223500e'
down_revision: Union[str, Sequence[str], None] = '7f1cdee3a012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('scripture_ref', sa.String(length=100), nullable=False),
    sa.Column('scripture_translation_id', sa.Integer(), nullable=False),
    sa.Column('scripture_text', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('application', sa.Text(), nullable=False),
    sa.Column('prayer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scripture_translation_id'], ['translations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_entry_date'), 'entries', ['entry_date'], unique=False)
    op.create_index('ix_entries_user_date_desc', 'entries', ['user_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_lower', sa.String(length=50), sa.Computed('lower(name)', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_lower', name='uq_tags_user_name_lower')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('entry_tags',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_index(op.f('ix_entry_tags_tag_id'), 'entry_tags', ['tag_id'], unique=False)
    op.create_table('entry_scripture_verses',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'verse_id')
    )
    op.create_index(op.f('ix_entry_scripture_verses_verse_id'), 'entry_scripture_verses', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_scripture_verses_verse_id'), table_name='entry_scripture_verses')
    op.drop_table('entry_scripture_verses')
    op.drop_index(op.f('ix_entry_tags_tag_id'), table_name='entry_tags')
    op.drop_table('entry_tags')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index('ix_entries_user_date_desc', table_name='entries')
    op.drop_index(op.f('ix_entries_entry_date'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
