"""add note fields and cross_references

Revision ID: 4708ebfdc41a
Revises: 9196d8cd4c53
Create Date: 2026-06-02 12:09:10.183242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4708ebfdc41a'
down_revision: Union[str, Sequence[str], None] = '9196d8cd4c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footnote_id', sa.Integer(), nullable=False),
    sa.Column('from_verse_id', sa.Integer(), nullable=False),
    sa.Column('to_book_id', sa.Integer(), nullable=False),
    sa.Column('to_chapter', sa.Integer(), nullable=False),
    sa.Column('to_verse_start', sa.Integer(), nullable=False),
    sa.Column('to_verse_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['footnote_id'], ['footnotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_references_footnote_id'), 'cross_references', ['footnote_id'], unique=False)
    op.create_index(op.f('ix_cross_references_from_verse_id'), 'cross_references', ['from_verse_id'], unique=False)
    op.create_index('ix_cross_references_to_target', 'cross_references', ['to_book_id', 'to_chapter', 'to_verse_start'], unique=False)
    # Batch mode: SQLite can only add a CHECK constraint by rebuilding the
    # table, so the columns and the constraint go in one block. (Autogenerate
    # does not emit the CHECK constraint for SQLite; added by hand.)
    with op.batch_alter_table('footnotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('char_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marker', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_check_constraint(
            'ck_footnotes_note_type',
            "note_type IN ('tn', 'sn', 'tc', 'map')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footnotes', schema=None) as batch_op:
        batch_op.drop_constraint('ck_footnotes_note_type', type_='check')
        batch_op.drop_column('ordinal')
        batch_op.drop_column('marker')
        batch_op.drop_column('char_offset')
        batch_op.drop_column('note_type')
    op.drop_index('ix_cross_references_to_target', table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_from_verse_id'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_footnote_id'), table_name='cross_references')
    op.drop_table('cross_references')
    # ### end Alembic commands ###
