"""add bible translation, book, chapter, verse, heading, footnote tables

Revision ID: 7f1cdee3a012
Revises: 58eedd3a95b9
Create Date: 2026-05-26 19:06:59.988974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1cdee3a012'
down_revision: Union[str, Sequence[str], None] = '58eedd3a95b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('copyright_notice', sa.String(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_code'), 'translations', ['code'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('translation_id', 'name', name='uq_books_translation_name'),
    sa.UniqueConstraint('translation_id', 'order_index', name='uq_books_translation_order')
    )
    op.create_index(op.f('ix_books_translation_id'), 'books', ['translation_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'number', name='uq_chapters_book_number')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_table('headings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('before_verse', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headings_chapter_id'), 'headings', ['chapter_id'], unique=False)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_red_letter', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'number', name='uq_verses_chapter_number')
    )
    op.create_index(op.f('ix_verses_chapter_id'), 'verses', ['chapter_id'], unique=False)
    op.create_table('footnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footnotes_verse_id'), 'footnotes', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_footnotes_verse_id'), table_name='footnotes')
    op.drop_table('footnotes')
    op.drop_index(op.f('ix_verses_chapter_id'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_headings_chapter_id'), table_name='headings')
    op.drop_table('headings')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_books_translation_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_translations_code'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
